global using LandaisSamuel_TP_DesignPatterns.Adapter;
global using LandaisSamuel_TP_DesignPatterns.Command;
global using LandaisSamuel_TP_DesignPatterns.Decorator;
global using LandaisSamuel_TP_DesignPatterns.Mediator;
global using LandaisSamuel_TP_DesignPatterns.Observer;
global using LandaisSamuel_TP_DesignPatterns.Singleton;
global using LandaisSamuel_TP_DesignPatterns.Strategy;
